### PR TITLE
API endpoint for namespace creation

### PR DESCRIPTION
**Pull request by romanblanco**
Parent issue: https://github.com/ansible/galaxy-dev/issues/180

- created a new endpoint to list namespaces: `/api/automation-hub/v3/namespaces/`
- implemented `POST` action to create a new namespace

TODO:
- [x] assign list of [groups](https://github.com/ansible/galaxy-api/pull/132/files#diff-501a88204e6d0fc39ef5ad9debd9e98dL40) implicitly while creating a new namespace
- [ ] unit tests

### CODE REVIEW

**Comment by romanblanco** [comment]
I'm using revert of https://github.com/ansible/galaxy-api/pull/126/ to get the `POST` form and test the API

**Comment by alikins** [comment]
@romanblanco Whats the difference between this new '/api/automation-hub/v3/namespaces/' endpoints and the existing `/api/automation-hub/v3/_ui/namespaces/'  endpoints?

**Comment by alikins** [comment]
@romanblanco issue  https://github.com/ansible/galaxy-dev/issues/180 says:

> In order to get UI for creating namespaces, API needs to be implemented first:

There is some existing support for creating namespaces via the /_ui/  endpoints.

Whats the plan for this? Seem like there are at least 3 approaches:
- replace `/v3/_ui/namespaces/`  with `/v3/namespaces/'
  - including updating ui code that using the /_ui/ endpoints
- provide '/v3/_ui/namespaces/'  _and_ `/v3/namespaces/'  ?
  - if so what, makes them different
- extend existing `/v3/_ui/namespaces/` to providing any thing missing needed for https://github.com/ansible/galaxy-dev/issues/180 ?

**Comment by romanblanco** [comment]
> @romanblanco issue [ansible/galaxy-dev#180](https://github.com/ansible/galaxy-dev/issues/180) says:
> 
> > In order to get UI for creating namespaces, API needs to be implemented first:
> 
> There is some existing support for creating namespaces via the /_ui/ endpoints.
> 
> Whats the plan for this? Seem like there are at least 3 approaches:
> 
>     * replace `/v3/_ui/namespaces/`  with `/v3/namespaces/'
>       
>       * including updating ui code that using the /_ui/ endpoints
> 
>     * provide '/v3/_ui/namespaces/'  _and_ `/v3/namespaces/'  ?
>       
>       * if so what, makes them different
> 
>     * extend existing `/v3/_ui/namespaces/` to providing any thing missing needed for [ansible/galaxy-dev#180](https://github.com/ansible/galaxy-dev/issues/180) ?

I would avoid having two namespace endpoints, as it could get difficult to maintain them.

Updating UI and unit tests could take some time.

@cutwater could you think of a reason not to replace `/v3/_ui/namespaces/` endpoint with the `/v3/namespaces/` endpoint added in this PR?

**Comment by romanblanco** [comment]
> Whats the difference between this new '/api/automation-hub/v3/namespaces/' endpoints and the existing `/api/automation-hub/v3/_ui/namespaces/' endpoints?

this allows to create a namespace

**Comment by romanblanco** [comment]
> There is some existing support for creating namespaces via the /_ui/ endpoints.

@alikins could you point me to the code that you're referring to?

**Comment by romanblanco** [comment]
This should be part of `/v3/_ui/namespaces`.

Closing this PR.

Continuing the work in https://github.com/ansible/galaxy-api/compare/master...romanblanco:issue180-ui-create

**Pull request closed without merging**
