### PR TITLE
Use django-prometheus to bootstrap prometheus metrics

### PR DESCRIPTION
**Pull request by alikins**
This uses the django-prometheus package to add a /metrics endpoint with some basic prometheus metrics provided.

Fixes: ansible/galaxy-dev#130

### CODE REVIEW

**Comment by alikins** [comment]
Needs some corresponding incoming galaxy-dev changes for testing locally.

**Comment by alikins** [comment]
@cutwater New changes should fix this I believe.

Question related to https://github.com/korfuri/django-prometheus/blob/master/documentation/exports.md#exporting-metrics-in-a-wsgi-application-with-multiple-processes-globally . The docs there mention:

> If uwsgi is not using lazy-apps (lazy-apps = true), there will be a file descriptors leak (tens to hundreds of fds on a single file) due to the way uwsgi forks processes to create workers.

Afaict, there isn't anything explicitly enabling lazy-apps, but I'm not sure where wsgi config is setup. Is this something we need to worry about?

**Comment by cutwater** [comment]
I think we should just use single process with multiple threads in uwsgi. It'll solve the problem.

**Comment by alikins** [comment]
@cutwater 

> I think we should just use single process with multiple threads in uwsgi. It'll solve the problem.

Is that something I should change in this PR?  Or in the nginx/uwsgi config (https://github.com/cutwater/automation-hub-deploy/blob/master/production/nginx/nginx-cfg/default.conf ?)

**Comment by alikins** [comment]
@cutwater or would that need to live in  a uwsgi config file? https://uwsgi.readthedocs.io/en/latest/Configuration.html

Should that live in the automation-hub-deploy repo or elsewhere?

**Comment by chouseknecht** [comment]
Looks like this is ready to be merged. Merging so that we can keep moving forward.

**Pull request merged**
